on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* */8 * * *'
jobs:
  update:
    runs-on: ubuntu-18.04
    name: auto update
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $PWD
          git clone https://yjcn:${{ secrets.GITHUB_TOKEN }}@github.com/yjcn/qBittorrent.git
          cd qBittorrent
          git remote add upstream https://github.com/qbittorrent/qBittorrent.git
          git fetch upstream
          git checkout master
          git config --global user.email "460990832@qq.com"
          git config --global user.name "yjcn"
          git merge upstream/master
          git push origin master 
      
