on:
  watch:
    types: [started]
jobs:
  update:
    runs-on: ubuntu-18.04
    name: auto update
    steps:
      - uses: actions/checkout@v2
      - run: |
          git remote add upstream https://github.com/qbittorrent/qBittorrent.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master 
      
